### PR TITLE
Implement `Debug` for `MultiMap`.

### PR DESCRIPTION
**Pull request by pyfisch**
There are many more trait implementations that would be useful for `MultiMap`. This is just the first one I need. `HashMap` implements many traits and most of them would be useful for `MultiMap` too.

### CODE REVIEW

**Comment by havarnov** [comment]
Good idea! Maybe a test? Something a la this (from the ::std::collections::HashMap):

``` rust
    #[test]
    fn test_show() {
        let mut map = HashMap::new();
        let empty: HashMap<i32, i32> = HashMap::new();

        map.insert(1, 2);
        map.insert(3, 4);

        let map_str = format!("{:?}", map);

        assert!(map_str == "{1: 2, 3: 4}" ||
                map_str == "{3: 4, 1: 2}");
        assert_eq!(format!("{:?}", empty), "{}");
    }
```

If you fix this i'll merge this pull request.

**Comment by havarnov** [comment]
Also, maybe you could open an issue for the missing traits you'd like to see? That way we can track progress and implement them without stepping on each others feet.

**Comment by pyfisch** [comment]
I added the proposed test case.

**Comment by havarnov** [comment]
I'm sorry I should have pointed out that the test I pasted in was from the HashMap implementation in the standard library. You'll have make a similar test for the MultiMap.

If you don't have time you can just remove the test and I'll add it later.

**Comment by pyfisch** [comment]
It's me I did not read the test. Now it is (hopefully) fixed.

**Comment by havarnov** [comment]
(thumbs up)

**Pull request merged**
