### PR TITLE
Fix or document panics when the vector for a key is empty

### PR DESCRIPTION
**Pull request by tormol**
Inspired by #36.

I saw the iterator bugs when working on #43, and found the rest by searching for `[0]`.

### CODE REVIEW

**Comment by havarnov** [comment]
Thanks, I'll look at it as soon as I find the time 👍

**Comment by havarnov** [comment]
I've just merge a couple of other PRs, would you like to fix the conflict? Apart from that this looks good 👍

**Comment by tormol** [comment]
Rebased & ran cargo fmt.

**Comment by havarnov** [comment]
I think I possibly merged something that caused a merge conflict, can you fix @tormol?

**Pull request merged**
