### PR TITLE
Implement serde's serialization traits and add tests

### PR DESCRIPTION
**Pull request by bow**
Hello @havarnov,

Being a wrapper around HashMap, I think it would be sensible if MultiMap can be (de)serialized using serde.

The implementation is quite straightforward: we just (de)serialize the inner HashMap, into maps of key => vector[value]. I also expose this as an optional feature of the crate, which is currently enabled by default. There is probably an argument for making the (de)serialization more fancy, e.g. when the value of a key is only one, extract it out from the vector. But I am interested in what your thoughts are on this first.

I added tests, but they are limited by the fact that `serde_test`'s `assert_tokens` function require a predefined ordering of the serialization tokens. Since HashMap, and by extension MultiMap, have an undefined sort order, putting in more than one key would make the test non deterministic. Again, I could work around this by implementing a custom `assert_tokens`, but I'm interested in what you thought about this first set of changes first.

Finally, I should mention that I actually stumbled on the need to do this in another crate where MultiMap was about to be used, two days ago. Serde 1.0 happened to be released yesterday and I found out that they have a remote derive feature that goes around Rust's limitation on trait implementations of structs not defined in the same crate. Despite this, I think it is still a good idea to have MultiMap optionally implement serde's traits, so I decided to go ahead with the PR :).

Anyway, thanks in advance for checking out.

### CODE REVIEW

**Comment by johanneskoester** [comment]
One question for my understanding:
Why can't we just use `#[derive(Serialize, Deserialize)]` here? As far as I know, serde is already implemented for `HashMap`.

**Comment by havarnov** [comment]
I was about to ask the same question. :)

I do support the idea that MultiMap should be serializable!

If you change the PR I'll merge.

**Comment by bow** [comment]
Oh yes, sorry I forgot to explain that :). And yes, that is possible (and would make it way simpler actually). I did it like this to make the serialized object deserializable into a regular HashMap (and the reverse too). So the MultiMap is transparent essentially, otherwise it would be a deserialized MultiMap struct.

I did wonder if this could be done by using one of their attributes, essentially just unwrapping the MultiMap. But I couldn't find this.

This was a deliberate choice by the way, and it's also up for discussion. Just using `derive` is also ok in my opinion.

**Comment by johanneskoester** [comment]
Mhm, at first sight I don't see an advantage in deserializing into a regular HashMap. You can always achieve that by first deserializing into MultiMap and then obtaining the inner HashMap. Since the difference in usability is minor, I would prefer the latter because it is less code and therefore better to maintain.

**Comment by bow** [comment]
@johanneskoester, it does indeed mean less burden of maintenance. Though I do feel that since `inner` is a private field of the `MultiMap` struct, it should not be leaked out when serializing.

But anyway, the change to use `derive` is simple and my latest push should show this. I've also updated the tests to reflect the fact. @havarnov can now choose either of the two derivations :).

**Comment by havarnov** [comment]
@bow, I think derive is the right way to do this.

But I do think this PR can be cleaned up some. I don't think the test add any value. They just test that serde does it's job. I don't think the feature flag is necessary. And is IT possible to drop the serde dependency and only add serde_derive?

I'm sorry that you have to scratch all your work. But the idea and PR is very welcome!

**Comment by bow** [comment]
@havarnov, no worries ~ if anything they let me dig deeper into serde itself ;). And sure, I'll clean it up as you'd like then. It is not possible to just use serde_derive and not serde, unfortunately. It seems that serde just provides the traits and serde_derive the macro for derive implementation without them depending on each other.

Anyway, my change should appear soon.

**Comment by bow** [comment]
Ah, sorry, I just saw I mistyped what I meant in the commit message :/. I meant to say `Update serde dependency to be required and remove tests`.

If it's not too much trouble, I'm fine with the change being cherry-picked (or actually, just squashed into one commit for that matter).

**Review by johanneskoester — APPROVED** [review]

**Comment by havarnov** [comment]
I'm sorry i haven't merge this PR yet. But I got second thoughts: maybe this feature should be behind a feature flag. Serde is a large dep. if you don't need it. What do you guys think? Is serde-derive even possible to have behind a feature flag?

**Comment by johanneskoester** [comment]
Would be fine for me. I don't know if it is possible though.

**Comment by bow** [comment]
I'm biased towards making it optional, but defaulting to including it as serde seems to be the de-facto serialization crate now (especially since [rustc-serialize is being deprecated](https://github.com/rust-lang-deprecated/rustc-serialize)).

I did include this in an earlier commit, but that was wrong. The correct way is to use something like `#[cfg(feature = "serde_impl")]` for the `extern crate` statements and `#[cfg_attr(feature = "serde_impl", derive(Serialize, Deserialize)]` for the derives.

If this is ok, I can push another change.

**Comment by havarnov** [comment]
@bow yes, include that change and I'll merge.

**Comment by bow** [comment]
Great, I've just pushed the change ~ you should be able to see it soon. Thanks again :)!

**Comment by kamalmarhubi** [comment]
Small post in favour of _not_ using `derive` for this. We don't see inner details of `BTreeMap` or `HashMap`, and I don't see why we should see inner details of `MultiMap`.

**Comment by kamalmarhubi** [comment]
To give a concrete example, I may have something like:

```rust
type User = String;
#[derive(Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
enum Permission {
    Read,
    Write,
    Delete,
}
struct UserPermissions {
    perms: MultiMap<User, Permission>,
}
```
I'd like to be able to deserialize from something like:

```json
{
    "user1": ["read"],
    "user2": ["read", "write"],
    "user3": ["read", "write", "delete"],
}
```

From what I can see, using `derive` on `MultiMap` makes this impossible. Or am I misunderstanding?

**Comment by johanneskoester** [comment]
Why that? Isn't this exactly what serde would do?

**Comment by bow** [comment]
As far as I understand, with just `derive(Serialize, Deserialize)`, @kamalmarhubi's example would need to be deserialized from this:

```
{
   "inner" : {
      "user1": ["read"],
      "user2": ["read", "write"],
      "user3": ["read", "write", "delete"]
    }
}
```

Not terribly inconvenient, but it does leak out the `inner` field of the `MultiMap` struct and I would guess that this is not what most users would expect since `inner` is not public. I do have a bias also towards removing the `inner` field (hence my initial implementation).

Still, I am ok with just using `derive` but I also don't mind putting back the initial `impl` if that's the consensus here, just so long as `MultiMap` is serde-compatible :).

**Comment by johanneskoester** [comment]
Ah, now I get the problem. Indeed, hiding inner makes in fact sense. What do you think @havarnov?

**Comment by havarnov** [comment]
Now I'm also enlightened 👍

I'm sorry for the back and forth @bow.

I suggest the following:
* we go back to the custom serialize/deserialize impl
* we keep the feature flag, which defaults to enabled

Any objections?

**Comment by bow** [comment]
No worries @havarnov ~ this is where git's commit history shows its usefulness :).

I'll push the changes soon, and may I also suggest re-adding the test, just to catch any regressions on our custom (de)serialize traits? After that, still feel free to cherry-pick and/or squash my changes to keep the `master` history clean if you like.

**Comment by bow** [comment]
All right, changes are pushed ~ almost the same as the first commit of this PR with a small change on the `cfg`, making it  used properly (I did some local tests, seems to behave as expected with and without the feature). The `serde_derive` dependency is now dropped and `serde_test` is re-added as a `dev-dependency` so it is only pulled for test compilations.

As always, let me know if any changes should be made (I still may have missed something).

**Comment by kamalmarhubi** [comment]
My only suggestion is to have serde support off by default rather than on. I think that serialization is a much less frequently needed feature than the multimap itself. Serde is a heavyweight dependency for something that otherwise only depends on std.

**Comment by bow** [comment]
I'm also ok if not using serde is the default feature. Most if not all of the crates I've been working with have some form of (de)serialization or depends on a crate that provides this (so I am biased), but indeed this is not true for all.

**Comment by havarnov** [comment]
I still think we should leave It on by default. As @bow says, most projects have some sort of serialization. And if it don't and the dependencies suddenly explodes I think most will investigate why and can then choose to disable the feature.

**Comment by bow** [comment]
Thank you @havarnov ~ Related to the merge, I am wondering if you have any plans on publishing soon? No rush of course, but it would be great to depend on a proper multimap version in `Cargo.toml` and not a git commit.

**Comment by kamalmarhubi** [comment]
@havarnov if there's to be a release, can we revisit #11?

**Comment by johanneskoester** [comment]
@havarnov can we get a new release please?

**Comment by havarnov** [comment]
@johanneskoester I'm sorry I haven't had the time. I'm going to publish a new version now :D

**Comment by havarnov** [comment]
@johanneskoester now 0.4.0 is published on crates.io :D

@kamalmarhubi I still think #11 is a too little change to defend a breaking change, sry.

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
